# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: OrdererOrg
    Domain: orderer.qedvault.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: admin
        SANS:
          - localhost
      - Hostname: manufacturer
        SANS:
          - localhost
      - Hostname: consumer
        SANS:
          - localhost
      - Hostname: reseller
        SANS:
          - localhost
  
  