version: "3.7"

volumes:
  orderer.example.com:
  peer0.org1.example.com:
  peer0.org2.example.com:


networks:
  test:
    name: fabric_test

services:
  ca.org1.example.com:
    image: hyperledger/fabric-ca:latest
    container_name: ca.org1.example.com
    labels:
      service: hyperledger-fabric
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_CA_CERTFILE=/myfiles/organization/ca/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/myfiles/organization/ca/priv_sk
      - FABRIC_CA_SERVER_TLS_CERTFILE=/myfiles/organization/peers/peer0.org1.example.com/tls/server.crt
      - FABRIC_CA_SERVER_TLS_KEYFILE=/myfiles/organization/peers/peer0.org1.example.com/tls/server.key
    ports:
      - "7054:7054"
      - "17054:17054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../organizations/fabric-ca/org1:/etc/hyperledger/fabric-ca-server
      - ../organizations/peerOrganizations/org1.example.com:/myfiles/organization
    networks:
      - test


  orderer.example.com:
    extends:
      file: ./docker-compose/compose-orderer.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    environment:
      - ORDERER_OPERATIONS_LISTENADDRESS=orderer.example.com:9443
    volumes:
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
        - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
        - ./.data/orderer.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      - 9443:9443
    networks:
      - test
  
  peer0.org1.example.com:
    extends:
      file: ./docker-compose/compose-org1.yaml
      service: peer-container

    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org1"}
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org1.example.com:9444
      
    volumes:
        - ../organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com:/etc/hyperledger/fabric
        - ./.data/peer0.org1.example.com:/var/hyperledger/production
        - ../chaincodes/src:/opt/gopath/my-chaincodes/
    ports:
      - 7051:7051
      - 7444:9444
    networks:
      - test
  
  peer1.org1.example.com:
    extends:
      file: ./docker-compose/compose-org1.yaml
      service: peer-container

    container_name: peer1.org1.example.com
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.example.com:7051
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer1org1"}
      - CORE_OPERATIONS_LISTENADDRESS=peer1.org1.example.com:9444

    volumes:
        - ../organizations/peerOrganizations/org1.example.com/peers/peer1.org1.example.com:/etc/hyperledger/fabric
        - ./.data/peer1.org1.example.com:/var/hyperledger/production
        - ../chaincodes/src:/opt/gopath/my-chaincodes/
    ports:
      - 9051:7051
      - 9444:9444
    networks:
      - test
  


  peer0.org2.example.com:
    extends:
      file: ./docker-compose/compose-org2.yaml
      service: peer-container

    container_name: peer0.org2.example.com
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org2.example.com:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CHAINCODE_AS_A_SERVICE_BUILDER_CONFIG={"peername":"peer0org2"}
      - CORE_OPERATIONS_LISTENADDRESS=peer0.org2.example.com:9444

    volumes:
        - ../organizations/peerOrganizations/org2.example.com/peers/peer0.org2.example.com:/etc/hyperledger/fabric
        - ./.data/peer0.org2.example.com:/var/hyperledger/production
        - ../chaincodes/src:/opt/gopath/my-chaincodes/
    ports:
      - 8051:7051
      - 8444:9444
    networks:
      - test

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=/etc/hyperledger/peercfg
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - ../packages:/opt/gopath/src/github.com/hyperledger/fabric/peer/packages
        - ../chaincodes:/opt/gopath/src/github.com/hyperledger/fabric/peer/chaincodes
        - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ../organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./core/core-peer-org1.yaml:/etc/hyperledger/peercfg/core.yaml
        - ../config/configtx/configtx1.yaml:/etc/hyperledger/peercfg/configtx.yaml
        # - ./core/core-peer-org2.yaml:/etc/hyperledger/peercfg/org2/core.yaml
    depends_on:
      - peer0.org1.example.com
      - peer0.org2.example.com
    networks:
      - test


